version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
    # depends_on:
    #   - db

  # db:
  #   platform: linux/x86_64
  #   image: mysql:5.7
  #   ports:
  #     - 13306:3306
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=db #mysqlサービス名を指定
  #     # - PMA_USER=root # なぜかコメントアウトしたらWindowsでphpMyAdminに接続できた
  #     # - PMA_PASSWORD=secret
  #   ports:
  #     - 8888:80
  #   depends_on:
  #     - db